name: simple-download
version: 0.0.3
synopsis: A simple wrapper of http-conduit for file download.
category: Web
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2016 Shao Cheng
license: BSD3
github: TerrorJack/simple-download

ghc-options: -Wall

default-extensions:
  - FlexibleContexts

extra-source-files:
  - README.md

dependencies:
  - base >= 4.8 && < 4.10
  - conduit-combinators
  - cryptonite
  - cryptonite-conduit
  - http-conduit
  - mtl
  - transformers

library:
  source-dirs: src
